version: "3.7"

services:
  app:
    env_file: 
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-redux-persist
    volumes: 
      - ".:/usr/src/app"
    ports:
      - "3001:3000"